-- AlterTable
ALTER TABLE "Blog" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "EmailVerificationChallenge" ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ USING "expiresAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Follow" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Guestbook" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "repliedAt" SET DATA TYPE TIMESTAMPTZ USING "repliedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC',
ALTER COLUMN "publishedAt" SET DATA TYPE TIMESTAMPTZ USING "publishedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "expiresAt" SET DATA TYPE TIMESTAMPTZ USING "expiresAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "emailVerified" SET DATA TYPE TIMESTAMPTZ USING "emailVerified" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';
