name: main
on:
  push:
    branches:
    - main

jobs:
  image:
    permissions:
      contents: read
      packages: write
      attestations: write
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - id: arch
      run: echo arch=arm64 >> "$GITHUB_OUTPUT"
    - uses: docker/build-push-action@v6
      with:
        pull: "true"
        push: "true"
        no-cache: "false"
        build-args:
          GIT_COMMIT=${{ github.sha }}
        tags: ghcr.io/${{ github.repository }}:git-${{ github.sha }}-${{ steps.arch.outputs.arch }}
        labels: |
          org.opencontainers.image.revision=${{ github.sha }}
        annotations: |
          org.opencontainers.image.title=Typo Blue
          org.opencontainers.image.description=ActivityPub-enabled text-only blogging platform
          org.opencontainers.image.url=https://typo.blue/
          org.opencontainers.image.source=https://github.com/yangnaru/typo-blue
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.licenses=AGPL-3.0-only
        cache-from:
          type=registry,ref=ghcr.io/${{ github.repository }}:build-cache-${{ steps.arch.outputs.arch }}
        cache-to:
          type=registry,ref=ghcr.io/${{ github.repository }}:build-cache-${{ steps.arch.outputs.arch }},mode=max
        provenance: false